name: Terraform CD

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write  # required for Workload Identity Federation

jobs:
  terraform-cd:
    if: github.event.pull_request.merged == true
    uses: rjones-projects/dne-pe-reusable-actions/.github/workflows/terraform-cd-reusable.yml@a0d86f49dcc3b628b9d29bc86807e16a5fd6716a  # main, no tag
    with:
      app_id: ${{ vars.APP_ID }}
      app_owner: ${{ github.repository_owner }}
    secrets: inherit
