name: Terraform CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  id-token: write  # required for Workload Identity Federation
#this is an example of how to use a reusable workflow for terraform ci.  The reusable workflow is in the rjones-projects/dne-pe-reusable-actions repo.  The reusable workflow is called terraform-ci-reusable.yml and is located in the .github/workflows directory of that repo.  The reusable workflow requires the following inputs:
jobs:
  terraform-ci: 
    uses: rjones-projects/dne-pe-reusable-actions/.github/workflows/terraform-ci-reusable.yml@a0d86f49dcc3b628b9d29bc86807e16a5fd6716a  # main, no tag
    with:
      enforce_governance: false
      run_module_tests: false
      gcp_project_id: idp-poc-495014
      app_id: ${{ vars.APP_ID }}
      app_owner: ${{ github.repository_owner }}
    secrets:
      NGDI_APP_PRIVATE_KEY: ${{ secrets.NGDI_APP_PRIVATE_KEY }}
      WIF_PROVIDER_URL: ${{ secrets.WIF_PROVIDER }}
      SA_NAME: ${{ secrets.WIF_SERVICE_ACCOUNT }}
